name: build

on:
  push:
  pull_request:

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore SamOnnxDemo/SamOnnxDemo.csproj
      - name: Build
        run: dotnet build -c Release SamOnnxDemo/SamOnnxDemo.csproj
